# Generated by Django 5.2.4 on 2025-07-08 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pass_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationMTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environnement', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=20, unique=True)),
                ('base_url', models.URLField()),
                ('collection_url', models.URLField()),
                ('user_id', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('subscription_key', models.CharField(max_length=100)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('country_code', models.CharField(default='CG', max_length=2)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('max_retries', models.IntegerField(default=3)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration MTN',
                'verbose_name_plural': 'Configurations MTN',
                'db_table': 'configurations_mtn',
            },
        ),
        migrations.CreateModel(
            name='TransactionMTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('financial_transaction_id', models.CharField(blank=True, max_length=100)),
                ('type_transaction', models.CharField(choices=[('request_to_pay', 'Request to Pay'), ('payment_status', 'Payment Status'), ('account_balance', 'Account Balance'), ('account_holder', 'Account Holder'), ('refund', 'Refund')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XAF', max_length=3)),
                ('payer_msisdn', models.CharField(max_length=15)),
                ('payee_msisdn', models.CharField(blank=True, max_length=15)),
                ('statut', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('status_reason', models.CharField(blank=True, max_length=100)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('callback_payload', models.JSONField(default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('nombre_tentatives', models.IntegerField(default=0)),
                ('derniere_erreur', models.TextField(blank=True)),
                ('paiement_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_mtn', to='pass_payments.paiementpass')),
            ],
            options={
                'verbose_name': 'Transaction MTN',
                'verbose_name_plural': 'Transactions MTN',
                'db_table': 'transactions_mtn',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LogMTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('method', models.CharField(blank=True, max_length=10)),
                ('url', models.URLField(blank=True)),
                ('headers', models.JSONField(default=dict)),
                ('request_body', models.JSONField(default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(default=dict)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_mtn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mtn_integration.transactionmtn')),
            ],
            options={
                'verbose_name': 'Log MTN',
                'verbose_name_plural': 'Logs MTN',
                'db_table': 'logs_mtn',
                'ordering': ['-timestamp'],
            },
        ),
    ]
