# Generated by Django 5.2.4 on 2025-07-08 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pass_clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_pass', models.CharField(max_length=20, unique=True)),
                ('nom_pass', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('accident', 'Accident'), ('sante', 'Santé'), ('epargne', 'Épargne'), ('funeraire', 'Funéraire'), ('mixte', 'Mixte')], max_length=30)),
                ('prix_minimum', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('prix_maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nombre_beneficiaires_max', models.IntegerField(default=6)),
                ('duree_validite_jours', models.IntegerField(default=365)),
                ('garanties', models.JSONField(default=dict)),
                ('souscription_mobile_money', models.BooleanField(default=True)),
                ('code_ussd', models.CharField(default='*128*6*6*1#', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('archive', 'Archivé')], default='actif', max_length=20)),
            ],
            options={
                'verbose_name': 'Produit PASS',
                'verbose_name_plural': 'Produits PASS',
                'db_table': 'produits_pass',
                'ordering': ['code_pass'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiairePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('telephone', models.CharField(blank=True, max_length=25)),
                ('relation_souscripteur', models.CharField(max_length=30)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('ordre_priorite', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('decede', 'Décédé')], default='actif', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('souscription_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaires', to='pass_clients.souscriptionpass')),
            ],
            options={
                'verbose_name': 'Bénéficiaire PASS',
                'verbose_name_plural': 'Bénéficiaires PASS',
                'db_table': 'beneficiaires_pass',
                'ordering': ['souscription_pass', 'ordre_priorite'],
                'unique_together': {('souscription_pass', 'ordre_priorite')},
            },
        ),
    ]
