# Generated by Django 5.2.4 on 2025-07-09 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pass_clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('telephone', models.CharField(max_length=25, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('agence', models.CharField(max_length=100)),
                ('poste', models.CharField(default='Agent Commercial', max_length=50)),
                ('adresse', models.TextField(blank=True)),
                ('solde_commissions', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('taux_commission', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('date_embauche', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
            ],
            options={
                'verbose_name': 'Agent NSIA',
                'verbose_name_plural': 'Agents NSIA',
                'db_table': 'agents',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='NumeroPolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_police', models.CharField(max_length=20, unique=True)),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('mode_attribution', models.CharField(choices=[('automatique', 'Automatique'), ('manuel', 'Manuel')], default='automatique', max_length=20)),
                ('commentaire_attribution', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('attribue', 'Attribué'), ('suspendu', 'Suspendu'), ('annule', 'Annulé')], default='attribue', max_length=20)),
                ('agent_attribueur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('souscription_pass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numero_police', to='pass_clients.souscriptionpass')),
            ],
            options={
                'verbose_name': 'Numéro de Police',
                'verbose_name_plural': 'Numéros de Police',
                'db_table': 'numeros_police_congo',
                'ordering': ['-date_attribution'],
            },
        ),
    ]
