# Generated by Django 5.2.4 on 2025-07-08 16:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pass_clients', '0002_initial'),
        ('pass_products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transaction', models.CharField(max_length=50, unique=True)),
                ('reference_mobile_money', models.CharField(blank=True, max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_transaction', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XAF', max_length=3)),
                ('operateur', models.CharField(choices=[('airtel_money', 'Airtel Money'), ('mtn_money', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire'), ('carte_bancaire', 'Carte bancaire')], max_length=20)),
                ('numero_payeur', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Format téléphone Congo: +242XXXXXXXX', regex='^\\+242[0-9]{8,9}$')])),
                ('code_confirmation', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('succes', 'Succès'), ('echec', 'Échec'), ('rembourse', 'Remboursé'), ('en_verification', 'En vérification'), ('expire', 'Expiré')], default='en_cours', max_length=30)),
                ('motif_echec', models.TextField(blank=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_comptabilisation', models.DateTimeField(blank=True, null=True)),
                ('type_paiement', models.CharField(choices=[('souscription_initiale', 'Souscription initiale'), ('cotisation', 'Cotisation'), ('renouvellement', 'Renouvellement'), ('rattrapage', 'Rattrapage')], default='cotisation', max_length=25)),
                ('commentaires', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paiements', to='pass_clients.clientpass')),
                ('souscription_pass', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paiements', to='pass_clients.souscriptionpass')),
            ],
            options={
                'verbose_name': 'Paiement PASS',
                'verbose_name_plural': 'Paiements PASS',
                'db_table': 'paiements_pass',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='SinistrePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sinistre', models.CharField(max_length=30, unique=True)),
                ('type_sinistre', models.CharField(choices=[('accident', 'Accident'), ('hospitalisation', 'Hospitalisation'), ('deces', 'Décès'), ('frais_medicaux', 'Frais médicaux'), ('indemnite_journaliere', 'Indemnité journalière'), ('frais_funeraires', 'Frais funéraires'), ('epargne_retraite', 'Épargne retraite')], max_length=50)),
                ('description_sinistre', models.TextField()),
                ('lieu_sinistre', models.CharField(blank=True, max_length=200)),
                ('date_sinistre', models.DateField()),
                ('montant_demande', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_accorde', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('statut', models.CharField(choices=[('declare', 'Déclaré'), ('en_instruction', 'En instruction'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('paye', 'Payé'), ('clos', 'Clos')], default='declare', max_length=30)),
                ('motif_rejet', models.TextField(blank=True)),
                ('documents_requis', models.JSONField(default=list)),
                ('documents_recus', models.JSONField(default=list)),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('commentaires_instruction', models.TextField(blank=True)),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinistres', to='pass_products.beneficiairepass')),
                ('instructeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinistres_instruits', to=settings.AUTH_USER_MODEL)),
                ('souscription_pass', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sinistres', to='pass_clients.souscriptionpass')),
            ],
            options={
                'verbose_name': 'Sinistre PASS',
                'verbose_name_plural': 'Sinistres PASS',
                'db_table': 'sinistres_pass',
                'ordering': ['-date_declaration'],
            },
        ),
    ]
