# Generated by Django 5.2.4 on 2025-07-24 07:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pass_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAirtel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Notre identifiant de transaction', max_length=100, unique=True)),
                ('airtel_transaction_id', models.CharField(blank=True, help_text='ID de transaction retourné par Airtel', max_length=100)),
                ('type_transaction', models.CharField(choices=[('debit_request', 'Debit Request'), ('payment_status', 'Payment Status'), ('account_balance', 'Account Balance'), ('refund', 'Refund')], default='debit_request', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant en XAF', max_digits=10)),
                ('devise', models.CharField(default='XAF', max_length=3)),
                ('payer_msisdn', models.CharField(help_text='Numéro du payeur (format international sans +)', max_length=15, validators=[django.core.validators.RegexValidator('^\\d{9,15}$', 'Format numéro invalide')])),
                ('payee_msisdn', models.CharField(blank=True, help_text='Numéro du bénéficiaire', max_length=15)),
                ('statut', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('status_reason', models.CharField(blank=True, help_text="Raison du statut (en cas d'échec)", max_length=100)),
                ('request_payload', models.JSONField(blank=True, help_text="Données envoyées à l'API Airtel", null=True)),
                ('response_payload', models.JSONField(blank=True, help_text="Réponse de l'API Airtel", null=True)),
                ('callback_payload', models.JSONField(blank=True, help_text='Données reçues du callback Airtel', null=True)),
                ('reference_client', models.CharField(default='NSIA PASS', help_text='Référence affichée côté client', max_length=100)),
                ('country', models.CharField(default='CG', max_length=2)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_callback', models.DateTimeField(blank=True, help_text='Date de réception du callback', null=True)),
                ('paiement_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_airtel', to='pass_payments.paiementpass')),
            ],
            options={
                'verbose_name': 'Transaction Airtel',
                'verbose_name_plural': 'Transactions Airtel',
                'db_table': 'airtel_transactions',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['external_id'], name='airtel_tran_externa_71528b_idx'), models.Index(fields=['airtel_transaction_id'], name='airtel_tran_airtel__2affce_idx'), models.Index(fields=['statut'], name='airtel_tran_statut_5f4d03_idx'), models.Index(fields=['date_creation'], name='airtel_tran_date_cr_817241_idx')],
            },
        ),
    ]
