# Generated by Django 5.2.4 on 2025-07-08 16:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('telephone', models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Format téléphone Congo: +242XXXXXXXX', regex='^\\+242[0-9]{8,9}$')])),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField()),
                ('operateur_mobile', models.CharField(blank=True, choices=[('airtel', 'Airtel'), ('mtn', 'MTN'), ('moov', 'Moov')], max_length=20, null=True)),
                ('numero_mobile_money', models.CharField(blank=True, max_length=25)),
                ('nombre_souscriptions_actives', models.IntegerField(default=0)),
                ('valeur_totale_souscriptions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date_premiere_souscription', models.DateTimeField(auto_now_add=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
            ],
            options={
                'verbose_name': 'Client PASS',
                'verbose_name_plural': 'Clients PASS',
                'db_table': 'clients_pass',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='SouscriptionPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_souscription', models.CharField(max_length=30, unique=True)),
                ('montant_souscription', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicite', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('annuelle', 'Annuelle'), ('unique', 'Paiement unique')], default='mensuelle', max_length=20)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('activee', 'Activée'), ('suspendue', 'Suspendue'), ('expiree', 'Expirée'), ('annulee', 'Annulée'), ('convertie_en_contrat', 'Convertie en contrat')], default='en_cours', max_length=30)),
                ('validation_automatique', models.BooleanField(default=True)),
                ('paiement_initial_recu', models.BooleanField(default=False)),
                ('date_souscription', models.DateTimeField(auto_now_add=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('transaction_mobile_money', models.CharField(blank=True, max_length=50)),
                ('operateur_paiement', models.CharField(blank=True, max_length=20)),
                ('commentaires', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='souscriptions', to='pass_clients.clientpass')),
            ],
            options={
                'verbose_name': 'Souscription PASS',
                'verbose_name_plural': 'Souscriptions PASS',
                'db_table': 'souscriptions_pass',
                'ordering': ['-date_souscription'],
            },
        ),
    ]
