# Generated by Django 5.2.4 on 2025-07-08 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pass_clients', '0001_initial'),
        ('pass_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscriptionpass',
            name='produit_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pass_products.produitpass'),
        ),
    ]
