# Generated by Django 5.2.4 on 2025-08-01 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borne_auth', '0001_initial'),
        ('pass_clients', '0002_initial'),
        ('pass_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscriptionpass',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent commercial qui a créé cette souscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='souscriptions', to='borne_auth.agent'),
        ),
        migrations.AddIndex(
            model_name='souscriptionpass',
            index=models.Index(fields=['numero_souscription'], name='souscriptio_numero__ec040d_idx'),
        ),
        migrations.AddIndex(
            model_name='souscriptionpass',
            index=models.Index(fields=['statut'], name='souscriptio_statut_98c3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='souscriptionpass',
            index=models.Index(fields=['agent'], name='souscriptio_agent_i_6bd785_idx'),
        ),
    ]
